import streamlit as st 
st.title('ALL ABOUT ME!')
st.header('기본 소개')
st.subheader('이름')
st.write('김주연')
st.write('金(성씨 김) 珠(구슬 주) 燕(잔치 연)')
st.write('<귀한 것(구슬)을 나누며(잔치) 살아라>는 뜻의 예쁜 이름을 가졌습니다!')
st.subheader('생년월일')
st.write('2000년 02월 03일')
st.write('특이한 것은 음력 생년월일은 1999년이고, 춘분 전에 태어나 2000년생임에도 토끼띠라는 것입니다!')
st.subheader('MBTI')
st.write('ENFP')
st.sidebar.selectbox('이 페이지가 재미있나요?', ['네', '아니오', '모르겠습니다'])
